// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
	"time"
)

type Branch struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Entry struct {
	ID     int64         `json:"id"`
	UserID sql.NullInt64 `json:"user_id"`
	// can be negative or positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Message struct {
	ID             int64         `json:"id"`
	WhoAskID       sql.NullInt64 `json:"who_ask_id"`
	WhoAnswerID    sql.NullInt64 `json:"who_answer_id"`
	Specialization sql.NullInt64 `json:"specialization"`
	MessageText    string        `json:"message_text"`
	Entries        sql.NullInt64 `json:"entries"`
	CreatedAt      time.Time     `json:"created_at"`
}

type Purchase struct {
	ID            int64           `json:"id"`
	FromAccountID sql.NullInt64   `json:"from_account_id"`
	AmountFiat    sql.NullFloat64 `json:"amount_fiat"`
	AmountCoins   sql.NullInt64   `json:"amount_coins"`
	CreatedAt     time.Time       `json:"created_at"`
}

type Setting struct {
	Rate sql.NullFloat64 `json:"rate"`
}

type Specialization struct {
	ID          int64         `json:"id"`
	Branch      sql.NullInt64 `json:"branch"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Online      sql.NullBool  `json:"online"`
}

type Transfer struct {
	ID            int64         `json:"id"`
	FromAccountID sql.NullInt64 `json:"from_account_id"`
	ToAccountID   sql.NullInt64 `json:"to_account_id"`
	CreatedAt     time.Time     `json:"created_at"`
}

type UserAccount struct {
	ID             int64     `json:"id"`
	Nickname       string    `json:"nickname"`
	Email          string    `json:"email"`
	Balance        int64     `json:"balance"`
	HashedPassword string    `json:"hashed_password"`
	Resp           bool      `json:"resp"`
	CreatedAt      time.Time `json:"created_at"`
}

type Withdraw struct {
	ID            int64           `json:"id"`
	FromAccountID sql.NullInt64   `json:"from_account_id"`
	AmountFiat    sql.NullFloat64 `json:"amount_fiat"`
	AmountCoins   sql.NullInt64   `json:"amount_coins"`
	CreatedAt     time.Time       `json:"created_at"`
}
