// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: service_adviceme.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdviceMeClient is the client API for AdviceMe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdviceMeClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserRsponse, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserRsponse, error)
}

type adviceMeClient struct {
	cc grpc.ClientConnInterface
}

func NewAdviceMeClient(cc grpc.ClientConnInterface) AdviceMeClient {
	return &adviceMeClient{cc}
}

func (c *adviceMeClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserRsponse, error) {
	out := new(CreateUserRsponse)
	err := c.cc.Invoke(ctx, "/pb.AdviceMe/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adviceMeClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserRsponse, error) {
	out := new(LoginUserRsponse)
	err := c.cc.Invoke(ctx, "/pb.AdviceMe/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdviceMeServer is the server API for AdviceMe service.
// All implementations must embed UnimplementedAdviceMeServer
// for forward compatibility
type AdviceMeServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserRsponse, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserRsponse, error)
	mustEmbedUnimplementedAdviceMeServer()
}

// UnimplementedAdviceMeServer must be embedded to have forward compatible implementations.
type UnimplementedAdviceMeServer struct {
}

func (UnimplementedAdviceMeServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserRsponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedAdviceMeServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserRsponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedAdviceMeServer) mustEmbedUnimplementedAdviceMeServer() {}

// UnsafeAdviceMeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdviceMeServer will
// result in compilation errors.
type UnsafeAdviceMeServer interface {
	mustEmbedUnimplementedAdviceMeServer()
}

func RegisterAdviceMeServer(s grpc.ServiceRegistrar, srv AdviceMeServer) {
	s.RegisterService(&AdviceMe_ServiceDesc, srv)
}

func _AdviceMe_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdviceMeServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdviceMe/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdviceMeServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdviceMe_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdviceMeServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdviceMe/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdviceMeServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdviceMe_ServiceDesc is the grpc.ServiceDesc for AdviceMe service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdviceMe_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AdviceMe",
	HandlerType: (*AdviceMeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _AdviceMe_CreateUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _AdviceMe_LoginUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_adviceme.proto",
}
